# Generated by Django 5.2 on 2026-05-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(default='Mehmet Akalın', max_length=100)),
                ('owner_title', models.CharField(default='Yazılım mühendisi', max_length=200)),
                ('owner_bio', models.TextField(blank=True, default="ROS2, Django ve React ile robotikten web'e uzanan sistemler geliştiriyorum.")),
                ('status_text', models.CharField(default='Aktif geliştirme yapıyor', max_length=100)),
                ('status_active', models.BooleanField(default=True)),
                ('skills', models.JSONField(default=list, help_text='JSON liste: ["Python", "Django", ...]')),
                ('github_url', models.URLField(blank=True, default='')),
                ('linkedin_url', models.URLField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Site Ayarları',
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
    ]
