# Generated by Django 5.2 on 2026-05-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cv_url',
            field=models.URLField(blank=True, default='', verbose_name='CV Dosyası URL'),
        ),
    ]
