# Generated by Django 5.1.5 on 2026-05-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_add_cv_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='owner_bio_en',
            field=models.TextField(blank=True, default='I build systems stretching from robotics to web using ROS2, Django, and React.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='owner_title_en',
            field=models.CharField(blank=True, default='Software engineer', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='status_text_en',
            field=models.CharField(blank=True, default='Actively developing', max_length=100, null=True),
        ),
    ]
