# Generated by Django 5.1.5 on 2026-05-28 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('site_settings', '0003_sitesettings_owner_bio_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='owner_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_settings_avatars', to='media.media', verbose_name='Profil Fotoğrafı'),
        ),
    ]
