# Generated by Django 5.1.5 on 2026-05-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_sitesettings_owner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_bio',
            field=models.TextField(blank=True, default='', verbose_name='Hakkımda Biyografisi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_bio_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Hakkımda Biyografisi (EN)'),
        ),
    ]
