# Generated by Django 5.2 on 2026-05-25 19:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(allow_unicode=True, max_length=180, unique=True)),
                ('description', models.TextField()),
                ('tech_stack', models.JSONField(default=list)),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('ARCHIVED', 'Arşivlendi'), ('IN_PROGRESS', 'Devam Ediyor')], db_index=True, default='ACTIVE', max_length=15)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('gallery', models.ManyToManyField(blank=True, related_name='project_gallery', to='media.media')),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_thumbnails', to='media.media')),
            ],
            options={
                'verbose_name': 'Proje',
                'verbose_name_plural': 'Projeler',
                'ordering': ['sort_order', '-id'],
                'indexes': [models.Index(fields=['slug'], name='projects_pr_slug_042165_idx'), models.Index(fields=['status'], name='projects_pr_status_f023cb_idx'), models.Index(fields=['sort_order'], name='projects_pr_sort_or_584f2d_idx')],
            },
        ),
    ]
