# Generated by Django 5.2 on 2026-05-26 15:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=150, verbose_name='Kurum / Şirket')),
                ('position', models.CharField(max_length=150, verbose_name='Pozisyon / Unvan')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Konum')),
                ('entry_type', models.CharField(choices=[('WORK', 'İş Deneyimi'), ('EDUCATION', 'Eğitim'), ('VOLUNTEER', 'Gönüllülük')], default='WORK', max_length=20, verbose_name='Tür')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('tech_stack', models.JSONField(blank=True, default=list, verbose_name='Teknolojiler')),
                ('start_date', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('is_current', models.BooleanField(default=False, verbose_name='Devam Ediyor')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Kariyer Kaydı',
                'verbose_name_plural': 'Kariyer Kayıtları',
                'ordering': ['-start_date', 'sort_order'],
            },
        ),
    ]
