# Generated by Django 5.1.5 on 2026-05-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerentry',
            name='company_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Kurum / Şirket (EN)'),
        ),
        migrations.AddField(
            model_name='careerentry',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama (EN)'),
        ),
        migrations.AddField(
            model_name='careerentry',
            name='location_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Konum (EN)'),
        ),
        migrations.AddField(
            model_name='careerentry',
            name='position_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Pozisyon / Unvan (EN)'),
        ),
    ]
