# Generated by Django 5.2 on 2026-05-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='publish_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Zamanlanmış Yayın'),
        ),
    ]
