# Generated by Django 5.1.5 on 2026-05-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_add_publish_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_html_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_json_en',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='summary_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
